import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Check, ChevronDown, Clipboard, FileText, Link2, Mail, Menu, Minus, Paperclip, Plus, Send, Smartphone, Trash2, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { generateEmailHtml } from './services/html.service';
import { templates } from './templates/templates';
import type { AttachmentItem, EmailDraft, EmailSection, TemplateId } from './types/email';

const initialDraft: EmailDraft = { from: '', to: '', cc: '', bcc: '', subject: 'A quick note from JSN Designs', greeting: 'Hi there,', title: 'A considered note', body: 'Thank you for your time. I wanted to share a thoughtful update with you.', sections: [{ id: crypto.randomUUID(), heading: 'The update', content: 'Add the details your recipient needs here.', bullets: [] }], closing: 'Warmly,', signature: 'JSN Designs\njsndesigns.com', ctaLabel: '', ctaUrl: '', template: 'professional' };

const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const splitRecipients = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);

export default function App() {
  const [draft, setDraft] = useState<EmailDraft>(() => { try { return JSON.parse(localStorage.getItem('jsn-mail-draft') || 'null') || initialDraft; } catch { return initialDraft; } });
  const [attachments, setAttachments] = useState<AttachmentItem[]>([]);
  const [device, setDevice] = useState<'desktop' | 'mobile'>('desktop');
  const [mode, setMode] = useState<'preview' | 'html'>('preview');
  const [account, setAccount] = useState<string>('Not connected');
  const [busy, setBusy] = useState<'test' | 'send' | null>(null);
  const [sent, setSent] = useState<{ recipient: string; subject: string; timestamp: string } | null>(null);

  const html = useMemo(() => generateEmailHtml(draft), [draft]);
  useEffect(() => { localStorage.setItem('jsn-mail-draft', JSON.stringify(draft)); }, [draft]);
  useEffect(() => { fetch('/api/email/config').then((response) => response.ok ? response.json() : null).then((data) => data?.gmailUser && setAccount(data.gmailUser)).catch(() => undefined); }, []);

  const update = (key: keyof EmailDraft, value: string | TemplateId) => setDraft((current) => ({ ...current, [key]: value }));
  const updateSection = (id: string, key: keyof EmailSection, value: string | string[]) => setDraft((current) => ({ ...current, sections: current.sections.map((section) => section.id === id ? { ...section, [key]: value } : section) }));
  const addSection = () => setDraft((current) => ({ ...current, sections: [...current.sections, { id: crypto.randomUUID(), heading: 'New section', content: '', bullets: [] }] }));
  const moveSection = (index: number, direction: -1 | 1) => setDraft((current) => { const sections = [...current.sections]; const next = index + direction; if (next < 0 || next >= sections.length) return current; [sections[index], sections[next]] = [sections[next], sections[index]]; return { ...current, sections }; });
  const removeSection = (id: string) => setDraft((current) => ({ ...current, sections: current.sections.filter((section) => section.id !== id) }));
  const handleFiles = (files: FileList | null) => { if (!files) return; const incoming = Array.from(files); const oversized = incoming.find((file) => file.size > 10 * 1024 * 1024); if (oversized) { toast.error(`${oversized.name} is over the 10 MB limit.`); return; } setAttachments((current) => [...current, ...incoming.map((file) => ({ id: crypto.randomUUID(), file }))]); };
  const saveDraft = () => { localStorage.setItem('jsn-mail-draft', JSON.stringify(draft)); toast.success('Draft saved locally'); };

  const send = async (kind: 'test' | 'send') => {
    if (!draft.to.trim() || !draft.subject.trim()) { toast.error('Add a recipient and subject first.'); return; }
    if (!splitRecipients(draft.to).every((email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))) { toast.error('Check the recipient email address.'); return; }
    setBusy(kind);
    try {
      const data = new FormData();
      data.append('payload', JSON.stringify({ ...draft, to: kind === 'test' ? account : draft.to }));
      attachments.forEach(({ file }) => data.append('attachments', file));
      const response = await fetch(`/api/email/${kind}`, { method: 'POST', body: data });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || 'Unable to send email');
      const timestamp = new Date().toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
      setSent({ recipient: kind === 'test' ? account : draft.to, subject: draft.subject, timestamp });
      toast.success(kind === 'test' ? 'Test email sent' : 'Email sent');
    } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to send email'); } finally { setBusy(null); }
  };

  return <div className="app-shell">
    <header className="topbar"><div className="brand-mark">JSN</div><div><div className="brand-name">JSN MAIL STUDIO</div><div className="brand-subtitle">Internal email builder</div></div><div className="topbar-spacer" /><div className="connection"><span className={`status-dot ${account === 'Not connected' ? 'offline' : ''}`} /> <span>{account === 'Not connected' ? 'Gmail not connected' : account}</span></div><button className="icon-button" aria-label="Open menu"><Menu size={19} /></button></header>
    <main className="workspace"><section className="editor-column"><div className="section-heading"><div><span className="eyebrow">Compose</span><h1>Build an email</h1></div><button className="text-button" onClick={() => { setDraft(initialDraft); setAttachments([]); }}>Clear draft <X size={15} /></button></div>
      <div className="panel account-panel"><div className="panel-icon"><Mail size={17} /></div><div><div className="field-label">From</div><div className="account-value">{account === 'Not connected' ? 'Connect Gmail in your .env file' : account}</div></div><span className="connected-pill"><Check size={13} /> {account === 'Not connected' ? 'Offline' : 'Connected'}</span></div>
      <div className="panel"><div className="panel-title"><span>Recipients</span><span className="panel-kicker">Comma separated</span></div><div className="field-grid"><Field label="To" value={draft.to} placeholder="name@company.com" onChange={(value) => update('to', value)} required /><Field label="CC" value={draft.cc} placeholder="Optional" onChange={(value) => update('cc', value)} /><Field label="BCC" value={draft.bcc} placeholder="Optional" onChange={(value) => update('bcc', value)} /><Field label="Subject" value={draft.subject} placeholder="Subject line" onChange={(value) => update('subject', value)} required full /></div></div>
      <div className="panel"><div className="panel-title"><span>Message</span><span className="panel-kicker">Plain, personal, precise</span></div><div className="field-stack"><Field label="Greeting" value={draft.greeting} onChange={(value) => update('greeting', value)} /><Field label="Email title" value={draft.title} onChange={(value) => update('title', value)} /><TextArea label="Body" value={draft.body} onChange={(value) => update('body', value)} rows={4} /></div></div>
      <div className="panel"><div className="panel-title"><span>Dynamic sections</span><button className="small-button" onClick={addSection}><Plus size={14} /> Add section</button></div>{draft.sections.map((section, index) => <div className="dynamic-section" key={section.id}><div className="section-tools"><span className="number-chip">{String(index + 1).padStart(2, '0')}</span><div className="tool-spacer" /><button className="mini-icon" title="Move up" onClick={() => moveSection(index, -1)} disabled={index === 0}><ArrowUp size={14} /></button><button className="mini-icon" title="Move down" onClick={() => moveSection(index, 1)} disabled={index === draft.sections.length - 1}><ArrowDown size={14} /></button><button className="mini-icon danger" title="Delete section" onClick={() => removeSection(section.id)}><Trash2 size={14} /></button></div><Field label="Heading" value={section.heading} onChange={(value) => updateSection(section.id, 'heading', value)} /><TextArea label="Content" value={section.content} onChange={(value) => updateSection(section.id, 'content', value)} rows={3} /><div className="field"><label>Bullet items <span>Optional, one per line</span></label><textarea value={section.bullets.join('\n')} onChange={(event) => updateSection(section.id, 'bullets', event.target.value.split('\n'))} placeholder="First item\nSecond item" rows={2} /></div></div>)}</div>
      <div className="panel"><div className="panel-title"><span>Sign-off</span></div><div className="field-stack"><Field label="Closing" value={draft.closing} onChange={(value) => update('closing', value)} /><TextArea label="Signature" value={draft.signature} onChange={(value) => update('signature', value)} rows={2} /></div><div className="cta-row"><div className="cta-heading"><Link2 size={16} /><span>Optional CTA button</span></div><div className="field-grid"><Field label="Button label" value={draft.ctaLabel} placeholder="View project" onChange={(value) => update('ctaLabel', value)} /><Field label="Destination URL" value={draft.ctaUrl} placeholder="https://" onChange={(value) => update('ctaUrl', value)} /></div></div></div>
      <div className="panel"><div className="panel-title"><span>Attachments</span><span className="panel-kicker">10 MB per file</span></div><label className="upload-zone"><Upload size={20} /><span><strong>Drop files here</strong> or browse</span><small>Multiple attachments supported</small><input type="file" multiple onChange={(event) => handleFiles(event.target.files)} /></label>{attachments.length > 0 && <div className="attachment-list">{attachments.map(({ id, file }) => <div className="attachment" key={id}><div className="file-icon"><FileText size={16} /></div><div><strong>{file.name}</strong><small>{formatBytes(file.size)}</small></div><button className="mini-icon danger" aria-label={`Remove ${file.name}`} onClick={() => setAttachments((current) => current.filter((item) => item.id !== id))}><X size={15} /></button></div>)}</div>}</div>
    </section><section className="preview-column"><div className="preview-header"><div><span className="eyebrow">Output</span><h2>Live preview</h2></div><div className="device-toggle"><button className={device === 'desktop' ? 'active' : ''} onClick={() => setDevice('desktop')}><Menu size={14} /> Desktop</button><button className={device === 'mobile' ? 'active' : ''} onClick={() => setDevice('mobile')}><Smartphone size={14} /> Mobile</button></div></div><div className="preview-panel"><div className="preview-toolbar"><div className="mode-tabs"><button className={mode === 'preview' ? 'active' : ''} onClick={() => setMode('preview')}>Preview</button><button className={mode === 'html' ? 'active' : ''} onClick={() => setMode('html')}>HTML</button></div><button className="copy-button" onClick={() => { navigator.clipboard.writeText(html); toast.success('HTML copied'); }}><Clipboard size={15} /> Copy HTML</button></div><div className={`preview-stage ${device}`}><div className="preview-frame">{mode === 'preview' ? <iframe title="Email preview" srcDoc={html} /> : <pre>{html}</pre>}</div></div><div className="template-picker"><div className="template-label">Template <ChevronDown size={14} /></div><div className="template-list">{templates.map((template) => <button key={template.id} className={`template-card ${draft.template === template.id ? 'selected' : ''}`} onClick={() => update('template', template.id)}><span className="template-swatch" style={{ background: template.accent }} /><span><strong>{template.name}</strong><small>{template.description}</small></span>{draft.template === template.id && <Check size={15} />}</button>)}</div></div></div></section></main>
    <footer className="actionbar"><div className="footer-note"><Paperclip size={15} /> {attachments.length} attachment{attachments.length === 1 ? '' : 's'} <span className="footer-divider" /> Autosaves locally</div><div className="actions"><button className="secondary-button" onClick={saveDraft}>Save draft</button><button className="secondary-button" onClick={() => send('test')} disabled={busy !== null}><Send size={15} /> {busy === 'test' ? 'Sending...' : 'Send test'}</button><button className="primary-button" onClick={() => send('send')} disabled={busy !== null}><Send size={15} /> {busy === 'send' ? 'Sending...' : 'Send email'}</button></div></footer>
    {sent && <div className="success-overlay" role="dialog" aria-modal="true"><div className="success-card"><button className="close-success" onClick={() => setSent(null)}><X size={17} /></button><div className="success-icon"><Check size={25} /></div><span className="eyebrow">Delivered</span><h2>Email sent</h2><p>Your message is on its way.</p><div className="sent-summary"><span>Recipient</span><strong>{sent.recipient}</strong><span>Subject</span><strong>{sent.subject}</strong><span>Timestamp</span><strong>{sent.timestamp}</strong></div><button className="primary-button full" onClick={() => setSent(null)}>Done</button></div></div>}
  </div>;
}

function Field({ label, value, placeholder, onChange, required, full }: { label: string; value: string; placeholder?: string; onChange: (value: string) => void; required?: boolean; full?: boolean }) { return <div className={`field ${full ? 'full' : ''}`}><label>{label}{required && <span className="required">*</span>}</label><input value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></div>; }
function TextArea({ label, value, onChange, rows }: { label: string; value: string; onChange: (value: string) => void; rows: number }) { return <div className="field"><label>{label}</label><textarea value={value} onChange={(event) => onChange(event.target.value)} rows={rows} /></div>; }
