import { useEffect, useMemo, useState } from 'react';
import { AlignCenter, AlignLeft, AlignRight, ArrowDown, ArrowUp, Check, ChevronDown, Clipboard, Copy, ExternalLink, FileText, Image, Link2, Mail, Menu, Minus, Paperclip, Plus, Rows3, Send, Smartphone, Table2, Trash2, Type, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { generateEmailHtml } from './services/html.service';
import { templates } from './templates/templates';
import type { AttachmentItem, EmailDraft, EmailSection, EmailTable, SectionBlock, TemplateId, TypographyStyle, TypographyTarget } from './types/email';
import logoUrl from './assets/JSN DESIGN.png';

const fonts = ['Arial, Helvetica, sans-serif', 'Georgia, serif', 'Verdana, sans-serif', 'Trebuchet MS, sans-serif'];
const style = (overrides: Partial<TypographyStyle> = {}): TypographyStyle => ({ fontFamily: fonts[0], fontSize: 15, fontWeight: 400, lineHeight: 1.6, letterSpacing: 0, textAlign: 'left', color: '#17211e', backgroundColor: '#ffffff', ...overrides });
const defaultStyles: Record<TypographyTarget, TypographyStyle> = { title: style({ fontSize: 28, fontWeight: 700, color: '#ffffff', backgroundColor: '#111111' }), heading: style({ fontSize: 18, fontWeight: 700 }), body: style(), list: style(), table: style(), button: style({ fontSize: 13, fontWeight: 700, color: '#ffffff', backgroundColor: '#1c5148', textAlign: 'center' }), signature: style({ fontSize: 14, fontWeight: 600 }) };
const newTable = (): EmailTable => ({ rows: [['Particular', 'Details', 'Status'], ['Vertical Logo', 'PNG / SVG / EPS / AF', 'Complete'], ['Horizontal Logo', 'PNG / SVG / EPS / AF', 'Complete']], header: true, align: 'left', fontSize: 13, fontWeight: 400, color: '#17211e', backgroundColor: '#edf4f0', borderColor: '#cedbd3', borderWidth: 1, cellPadding: 10 });
const block = (type: SectionBlock['type']): SectionBlock => ({ id: crypto.randomUUID(), type, content: type === 'paragraph' ? 'Add a paragraph to your email.' : '', items: type === 'list' ? ['First item', 'Second item'] : [], ordered: false, imageUrl: '', imageAlt: '', ctaLabel: type === 'cta' ? 'View details' : '', ctaUrl: '', table: type === 'table' ? newTable() : undefined });
const initialDraft: EmailDraft = { from: '', to: '', cc: '', bcc: '', subject: 'A considered note from JSN Designs', greeting: 'Hi there,', title: 'A considered note', body: 'Thank you for your time. I wanted to share a thoughtful update with you.', sections: [{ id: crypto.randomUUID(), heading: 'The update', content: '', bullets: [], blocks: [block('paragraph')] }], closing: 'Warmly,', signature: 'JSN Designs\njsndesigns.com', ctaLabel: '', ctaUrl: '', template: 'professional', typography: defaultStyles };
const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const recipients = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
const normalizeDraft = (draft: EmailDraft): EmailDraft => ({ ...initialDraft, ...draft, typography: { ...defaultStyles, ...(draft.typography || {}) }, sections: (draft.sections || []).map((section) => ({ ...section, blocks: section.blocks?.length ? section.blocks : [block('paragraph')] })) });

export default function App() {
  const [draft, setDraft] = useState<EmailDraft>(() => { try { return normalizeDraft(JSON.parse(localStorage.getItem('jsn-mail-draft') || 'null') || initialDraft); } catch { return initialDraft; } });
  const [attachments, setAttachments] = useState<AttachmentItem[]>([]); const [device, setDevice] = useState<'desktop' | 'mobile'>('desktop'); const [mode, setMode] = useState<'preview' | 'html'>('preview'); const [target, setTarget] = useState<TypographyTarget>('body'); const [account, setAccount] = useState('Not connected'); const [busy, setBusy] = useState<'test' | 'send' | null>(null); const [sent, setSent] = useState<{ recipient: string; subject: string; timestamp: string } | null>(null);
  const html = useMemo(() => generateEmailHtml(draft, logoUrl), [draft]);
  useEffect(() => { localStorage.setItem('jsn-mail-draft', JSON.stringify(draft)); }, [draft]);
  useEffect(() => { fetch('/api/email/config').then((response) => response.ok ? response.json() : null).then((data) => data?.gmailUser && setAccount(data.gmailUser)).catch(() => undefined); }, []);
  const update = (key: keyof EmailDraft, value: string | TemplateId) => setDraft((current) => ({ ...current, [key]: value }));
  const updateStyle = (key: keyof TypographyStyle, value: string | number) => setDraft((current) => ({ ...current, typography: { ...current.typography, [target]: { ...current.typography[target], [key]: value } } }));
  const updateSection = (id: string, patch: Partial<EmailSection>) => setDraft((current) => ({ ...current, sections: current.sections.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const updateBlock = (sectionId: string, blockId: string, patch: Partial<SectionBlock>) => setDraft((current) => ({ ...current, sections: current.sections.map((section) => section.id === sectionId ? { ...section, blocks: (section.blocks || []).map((item) => item.id === blockId ? { ...item, ...patch } : item) } : section) }));
  const addSection = () => setDraft((current) => ({ ...current, sections: [...current.sections, { id: crypto.randomUUID(), heading: 'New section', content: '', bullets: [], blocks: [block('paragraph')] }] }));
  const moveSection = (index: number, direction: -1 | 1) => setDraft((current) => { const sections = [...current.sections]; const next = index + direction; if (next < 0 || next >= sections.length) return current; [sections[index], sections[next]] = [sections[next], sections[index]]; return { ...current, sections }; });
  const handleFiles = (files: FileList | null) => { if (!files) return; const incoming = Array.from(files); const bad = incoming.find((file) => file.size > 10 * 1024 * 1024); if (bad) { toast.error(`${bad.name} is over the 10 MB limit.`); return; } setAttachments((current) => [...current, ...incoming.map((file) => ({ id: crypto.randomUUID(), file }))]); };
  const send = async (kind: 'test' | 'send') => { if (!draft.to.trim() || !draft.subject.trim()) return toast.error('Add a recipient and subject first.'); if (!recipients(draft.to).every((email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))) return toast.error('Check the recipient email address.'); setBusy(kind); try { const data = new FormData(); data.append('payload', JSON.stringify({ ...draft, to: kind === 'test' ? account : draft.to })); attachments.forEach(({ file }) => data.append('attachments', file)); const response = await fetch(`/api/email/${kind}`, { method: 'POST', body: data }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to send email'); const timestamp = new Date().toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }); setSent({ recipient: kind === 'test' ? account : draft.to, subject: draft.subject, timestamp }); toast.success(kind === 'test' ? 'Test email sent' : 'Email sent'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to send email'); } finally { setBusy(null); } };
  const clearDraft = () => { setDraft(initialDraft); setAttachments([]); toast.success('Draft cleared'); };
  return <div className="app-shell"><header className="topbar"><img className="brand-logo" src={logoUrl} alt="JSN Designs" /><div className="brand-divider" /><div><div className="brand-name">MAIL STUDIO</div><div className="brand-subtitle">Internal email builder</div></div><div className="topbar-spacer" /><div className="connection"><span className={`status-dot ${account === 'Not connected' ? 'offline' : ''}`} /><span>{account === 'Not connected' ? 'Gmail not connected' : account}</span></div><button className="icon-button" aria-label="Open menu"><Menu size={18} /></button></header>
    <main className="workspace"><section className="editor-column"><div className="section-heading"><div><span className="eyebrow">Compose / 01</span><h1>Build an email</h1></div><button className="text-button" onClick={clearDraft}>Clear draft <X size={14} /></button></div>
      <div className="panel account-panel"><div className="panel-icon"><Mail size={16} /></div><div><div className="field-label">From</div><div className="account-value">{account === 'Not connected' ? 'Connect Gmail in your .env file' : account}</div></div><span className="connected-pill"><Check size={12} /> {account === 'Not connected' ? 'Offline' : 'Connected'}</span></div>
      <Panel title="Recipients" kicker="Comma separated"><div className="field-grid"><Field label="To" value={draft.to} placeholder="name@company.com" onChange={(value) => update('to', value)} required /><Field label="CC" value={draft.cc} placeholder="Optional" onChange={(value) => update('cc', value)} /><Field label="BCC" value={draft.bcc} placeholder="Optional" onChange={(value) => update('bcc', value)} /><Field label="Subject" value={draft.subject} onChange={(value) => update('subject', value)} required full /></div></Panel>
      <Panel title="Message" kicker="Your content stays yours"><div className="field-stack"><Field label="Greeting" value={draft.greeting} onChange={(value) => update('greeting', value)} /><Field label="Title" value={draft.title} onChange={(value) => update('title', value)} /><TextArea label="Body" value={draft.body} onChange={(value) => update('body', value)} rows={4} /></div></Panel>
      <Panel title="Typography" kicker="Independent styles"><div className="type-targets">{(['title', 'heading', 'body', 'list', 'table', 'button', 'signature'] as TypographyTarget[]).map((item) => <button key={item} className={target === item ? 'active' : ''} onClick={() => setTarget(item)}><Type size={13} /> {item}</button>)}</div><TypographyControls value={draft.typography[target]} update={updateStyle} /></Panel>
      <Panel title="Sections" action={<button className="small-button" onClick={addSection}><Plus size={14} /> Add section</button>}>{draft.sections.map((section, index) => <SectionEditor key={section.id} section={section} index={index} total={draft.sections.length} updateSection={updateSection} updateBlock={updateBlock} moveSection={moveSection} removeSection={(id) => setDraft((current) => ({ ...current, sections: current.sections.filter((item) => item.id !== id) }))} />)}</Panel>
      <Panel title="Sign-off"><div className="field-stack"><Field label="Closing" value={draft.closing} onChange={(value) => update('closing', value)} /><TextArea label="Signature" value={draft.signature} onChange={(value) => update('signature', value)} rows={2} /></div><div className="cta-row"><div className="cta-heading"><Link2 size={15} /> Optional CTA button</div><div className="field-grid"><Field label="Button label" value={draft.ctaLabel} placeholder="View project" onChange={(value) => update('ctaLabel', value)} /><Field label="Destination URL" value={draft.ctaUrl} placeholder="https://" onChange={(value) => update('ctaUrl', value)} /></div></div></Panel>
      <Panel title="Attachments" kicker="10 MB per file"><label className="upload-zone"><Upload size={19} /><span><strong>Drop files here</strong> or browse</span><small>Multiple attachments supported</small><input type="file" multiple onChange={(event) => handleFiles(event.target.files)} /></label>{attachments.length > 0 && <div className="attachment-list">{attachments.map(({ id, file }) => <div className="attachment" key={id}><div className="file-icon"><FileText size={16} /></div><div><strong>{file.name}</strong><small>{formatBytes(file.size)}</small></div><button className="mini-icon danger" onClick={() => setAttachments((current) => current.filter((item) => item.id !== id))}><X size={15} /></button></div>)}</div>}</Panel>
    </section><section className="preview-column"><div className="preview-header"><div><span className="eyebrow">Output / 02</span><h2>Live preview</h2></div><div className="device-toggle"><button className={device === 'desktop' ? 'active' : ''} onClick={() => setDevice('desktop')}><Menu size={14} /> Desktop</button><button className={device === 'mobile' ? 'active' : ''} onClick={() => setDevice('mobile')}><Smartphone size={14} /> Mobile</button></div></div><div className="preview-panel"><div className="preview-toolbar"><div className="mode-tabs"><button className={mode === 'preview' ? 'active' : ''} onClick={() => setMode('preview')}>Preview</button><button className={mode === 'html' ? 'active' : ''} onClick={() => setMode('html')}>HTML</button></div><button className="copy-button" onClick={() => { navigator.clipboard.writeText(html); toast.success('HTML copied'); }}><Clipboard size={14} /> Copy HTML</button></div><div className={`preview-stage ${device}`}><div className="preview-frame">{mode === 'preview' ? <iframe title="Email preview" srcDoc={html} /> : <pre>{html}</pre>}</div></div><div className="template-picker"><div className="template-label">Design direction <ChevronDown size={13} /></div><div className="template-list">{templates.map((template) => <button key={template.id} className={`template-card ${draft.template === template.id ? 'selected' : ''}`} onClick={() => update('template', template.id)}><span className="template-swatch" style={{ background: template.accent }} /><span><strong>{template.name}</strong><small>{template.description}</small></span>{draft.template === template.id && <Check size={14} />}</button>)}</div></div></div></section></main>
    <footer className="actionbar"><div className="footer-note"><Paperclip size={14} /> {attachments.length} attachment{attachments.length === 1 ? '' : 's'} <span className="footer-divider" /> Autosaves locally</div><div className="actions"><button className="secondary-button" onClick={() => { localStorage.setItem('jsn-mail-draft', JSON.stringify(draft)); toast.success('Draft saved locally'); }}>Save draft</button><button className="secondary-button" onClick={() => send('test')} disabled={busy !== null}><Send size={14} /> {busy === 'test' ? 'Sending...' : 'Send test'}</button><button className="primary-button" onClick={() => send('send')} disabled={busy !== null}><Send size={14} /> {busy === 'send' ? 'Sending...' : 'Send email'}</button></div></footer>
    {sent && <div className="success-overlay" role="dialog" aria-modal="true"><div className="success-card"><button className="close-success" onClick={() => setSent(null)}><X size={16} /></button><div className="success-icon"><Check size={24} /></div><span className="eyebrow">Delivered</span><h2>Email sent</h2><p>Your message is on its way.</p><div className="sent-summary"><span>Recipient</span><strong>{sent.recipient}</strong><span>Subject</span><strong>{sent.subject}</strong><span>Timestamp</span><strong>{sent.timestamp}</strong></div><button className="primary-button full" onClick={() => setSent(null)}>Done</button></div></div>}</div>;
}

function Panel({ title, kicker, action, children }: { title: string; kicker?: string; action?: React.ReactNode; children: React.ReactNode }) { return <div className="panel"><div className="panel-title"><span>{title}</span><span className="panel-right">{action}{kicker && <span className="panel-kicker">{kicker}</span>}</span></div>{children}</div>; }
function Field({ label, value, placeholder, onChange, required, full }: { label: string; value: string; placeholder?: string; onChange: (value: string) => void; required?: boolean; full?: boolean }) { return <div className={`field ${full ? 'full' : ''}`}><label>{label}{required && <span className="required">*</span>}</label><input value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></div>; }
function TextArea({ label, value, onChange, rows }: { label: string; value: string; onChange: (value: string) => void; rows: number }) { return <div className="field"><label>{label}</label><textarea value={value} onChange={(event) => onChange(event.target.value)} rows={rows} /></div>; }
function TypographyControls({ value, update }: { value: TypographyStyle; update: (key: keyof TypographyStyle, value: string | number) => void }) { return <div className="type-controls"><div className="field"><label>Font family</label><select value={value.fontFamily} onChange={(event) => update('fontFamily', event.target.value)}>{fonts.map((font) => <option key={font}>{font}</option>)}</select></div><div className="control-grid"><Field label="Size" value={String(value.fontSize)} onChange={(next) => update('fontSize', Number(next) || 1)} /><Field label="Weight" value={String(value.fontWeight)} onChange={(next) => update('fontWeight', Number(next) || 400)} /><Field label="Line height" value={String(value.lineHeight)} onChange={(next) => update('lineHeight', Number(next) || 1)} /><Field label="Letter spacing" value={String(value.letterSpacing)} onChange={(next) => update('letterSpacing', Number(next) || 0)} /></div><div className="control-grid"><ColorField label="Text color" value={value.color} onChange={(next) => update('color', next)} /><ColorField label="Background" value={value.backgroundColor} onChange={(next) => update('backgroundColor', next)} /></div><div className="align-control"><span>Alignment</span>{(['left', 'center', 'right'] as const).map((align) => <button key={align} className={value.textAlign === align ? 'active' : ''} onClick={() => update('textAlign', align)}>{align === 'left' ? <AlignLeft size={14} /> : align === 'center' ? <AlignCenter size={14} /> : <AlignRight size={14} />}</button>)}</div></div>; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div className="color-field"><label>{label}</label><div><input type="color" value={value === 'transparent' ? '#ffffff' : value} onChange={(event) => onChange(event.target.value)} /><input value={value} onChange={(event) => onChange(event.target.value)} /></div></div>; }
function SectionEditor({ section, index, total, updateSection, updateBlock, moveSection, removeSection }: { section: EmailSection; index: number; total: number; updateSection: (id: string, patch: Partial<EmailSection>) => void; updateBlock: (sectionId: string, blockId: string, patch: Partial<SectionBlock>) => void; moveSection: (index: number, direction: -1 | 1) => void; removeSection: (id: string) => void }) { const blocks = section.blocks || []; const duplicate = () => updateSection(section.id, { blocks: [...blocks, ...blocks.map((item) => ({ ...item, id: crypto.randomUUID() }))] }); return <div className="dynamic-section"><div className="section-tools"><span className="number-chip">{String(index + 1).padStart(2, '0')}</span><div className="tool-spacer" /><button className="mini-icon" title="Move up" onClick={() => moveSection(index, -1)} disabled={index === 0}><ArrowUp size={13} /></button><button className="mini-icon" title="Move down" onClick={() => moveSection(index, 1)} disabled={index === total - 1}><ArrowDown size={13} /></button><button className="mini-icon" title="Duplicate section" onClick={duplicate}><Copy size={13} /></button><button className="mini-icon danger" title="Delete section" onClick={() => removeSection(section.id)}><Trash2 size={13} /></button></div><Field label="Heading" value={section.heading} onChange={(value) => updateSection(section.id, { heading: value })} /><div className="block-list">{blocks.map((item) => <BlockEditor key={item.id} block={item} update={(patch) => updateBlock(section.id, item.id, patch)} remove={() => updateSection(section.id, { blocks: blocks.filter((blockItem) => blockItem.id !== item.id) })} />)}</div><div className="block-add"><select value="" onChange={(event) => { if (event.target.value) updateSection(section.id, { blocks: [...blocks, block(event.target.value as SectionBlock['type'])] }); }}><option value="">Add content block...</option><option value="paragraph">Paragraph</option><option value="list">Bullet / numbered list</option><option value="image">Image</option><option value="cta">CTA button</option><option value="divider">Divider</option><option value="table">Table</option></select><Plus size={14} /></div></div>; }
function BlockEditor({ block: item, update, remove }: { block: SectionBlock; update: (patch: Partial<SectionBlock>) => void; remove: () => void }) { return <div className="block-editor"><div className="block-header"><span>{item.type === 'table' ? <Table2 size={14} /> : item.type === 'image' ? <Image size={14} /> : item.type === 'cta' ? <ExternalLink size={14} /> : item.type === 'divider' ? <Minus size={14} /> : <Rows3 size={14} />} {item.type}</span><button className="mini-icon danger" onClick={remove}><X size={13} /></button></div>{item.type === 'paragraph' && <TextArea label="Paragraph" value={item.content} onChange={(value) => update({ content: value })} rows={3} />}{item.type === 'list' && <><div className="field"><label>List style</label><select value={item.ordered ? 'numbered' : 'bullets'} onChange={(event) => update({ ordered: event.target.value === 'numbered' })}><option value="bullets">Bullets</option><option value="numbered">Numbered</option></select></div><TextArea label="Items, one per line" value={item.items.join('\n')} onChange={(value) => update({ items: value.split('\n') })} rows={3} /></>}{item.type === 'image' && <div className="field-grid"><Field label="Image URL" value={item.imageUrl} placeholder="https://" onChange={(value) => update({ imageUrl: value })} /><Field label="Alt text" value={item.imageAlt} onChange={(value) => update({ imageAlt: value })} /></div>}{item.type === 'cta' && <div className="field-grid"><Field label="Label" value={item.ctaLabel} onChange={(value) => update({ ctaLabel: value })} /><Field label="URL" value={item.ctaUrl} placeholder="https://" onChange={(value) => update({ ctaUrl: value })} /></div>}{item.type === 'table' && item.table && <TableEditor value={item.table} update={(table) => update({ table })} />}</div>; }
function TableEditor({ value, update }: { value: EmailTable; update: (value: EmailTable) => void }) { const patch = (next: Partial<EmailTable>) => update({ ...value, ...next }); const rows = value.rows; const setCell = (row: number, column: number, content: string) => patch({ rows: rows.map((current, rowIndex) => rowIndex === row ? current.map((cell, cellIndex) => cellIndex === column ? content : cell) : current) }); const addRow = () => patch({ rows: [...rows, rows[0].map(() => '')] }); const addColumn = () => patch({ rows: rows.map((row) => [...row, '']) }); const removeRow = () => rows.length > 1 && patch({ rows: rows.slice(0, -1) }); const removeColumn = () => rows[0].length > 1 && patch({ rows: rows.map((row) => row.slice(0, -1)) }); return <div className="table-editor"><div className="table-actions"><button onClick={addRow}><Plus size={12} /> Row</button><button onClick={addColumn}><Plus size={12} /> Column</button><button onClick={removeRow}><Minus size={12} /> Row</button><button onClick={removeColumn}><Minus size={12} /> Column</button><label><input type="checkbox" checked={value.header} onChange={(event) => patch({ header: event.target.checked })} /> Header row</label></div><div className="table-scroll"><table><tbody>{rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, columnIndex) => <td key={columnIndex}><input value={cell} onChange={(event) => setCell(rowIndex, columnIndex, event.target.value)} placeholder={rowIndex === 0 ? 'Header' : 'Cell'} /></td>)}</tr>)}</tbody></table></div><div className="table-settings"><ColorField label="Text" value={value.color} onChange={(color) => patch({ color })} /><ColorField label="Header" value={value.backgroundColor} onChange={(backgroundColor) => patch({ backgroundColor })} /><ColorField label="Border" value={value.borderColor} onChange={(borderColor) => patch({ borderColor })} /><Field label="Padding" value={String(value.cellPadding)} onChange={(cellPadding) => patch({ cellPadding: Number(cellPadding) || 0 })} /></div></div>; }
